from ray.rllib.core import DEFAULT_POLICY_ID

INTRINSIC_REWARD_MODULE_ID = "intrinsic_reward_module"
# INTRINSIC_REWARD_MODULE_ID = DEFAULT_POLICY_ID
# PPO_AGENT_POLICY_ID = "custom_ppo_module_id"
PPO_AGENT_POLICY_ID = DEFAULT_POLICY_ID

COL_EX_IN_VF_PREDS = "EX_IN_VF_PREDS"
COL_EX_VF_PREDS = "EX_VF_PREDS"
